# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a9fbe1c16d3db5f58aa444bff1eb98e9"
name = "schema-advanced-app"
application_url = "https://polls-indexes-two-mhz.trycloudflare.com"
embedded = true
handle = "schema-advanced-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://polls-indexes-two-mhz.trycloudflare.com/auth/callback", "https://polls-indexes-two-mhz.trycloudflare.com/auth/shopify/callback", "https://polls-indexes-two-mhz.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
